### ISSUE TITLE
Make a layer diagram

### ISSUE THREAD

**Issue by anthonyle17** [aa-software2112/SOEN390_SimpleCamera#10]
Represent the layers of the app, highest level on top. It is the development view of the 4 +1 architectural views. Example: the main activity that includes all modules should be on top

Source Story: #6
[Story points: 2] 
[Ideal hours: 1]

**Comment by samgo1** [comment]
The diagram can be viewed here: https://drive.google.com/file/d/1zJYEzX3DGvuYYqA6naBTX-YqIrvyQHZp/view?usp=sharing

**Comment by samgo1** [comment]
@laurawheatley to edit you have to go straight from the google drive because the link I posted is read-only

**Comment by samgo1** [comment]
@aa-software2112 @lkadian the architectural layer diagram is up on the google drive under Release 1 Documents/Diagrams. Layers on top have depencies on the layers that are under. Each layer has a color associated and every box represent a class. These will be the classes used for the class diagram, so a component = a class, really... and connectors means association therefore dependency. Give me your thoughts on this

**Comment by lkadian** [comment]
Looks good @samgo1 I will use these for the class diagram. Can you add this diagram to the wiki under Architecture section?

**Comment by samgo1** [comment]
Yes its there
