### ISSUE TITLE
Create mockup

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#17]
As a developer, I would like to create a mockup of the  Countdown Timer #16 feature to be able to validate the implementation vision.

- [x] Add "X" to mockup that replaces original "clock" symbol when timer is set @Lussier115 

Link to the [wiki](https://github.com/aa-software2112/SOEN390_SimpleCamera/wiki/Mockups) 
Source Story: #16
[Story points: 1]
[Ideal hours: 2]

**Comment by aa-software2112** [comment]
Why is his marked as done? We haven’t seen the mock-up as a team yet to discuss potential changes

**Comment by Lussier115** [comment]
Yeah makes sense, we added a mockup for now in the wiki so that everyone can see, if we end up doing changes I will update it afterward.

**Comment by anthonyle17** [comment]
Updated mockup looks good with the new feature of cancelling the timer while the countdown is running

**Comment by aa-software2112** [comment]
Seems good, I'm going to close this.
