### ISSUE TITLE
Implement backend

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#20]
Implement backend for Capture Time Delay

Source Story: #16
[Story points: 2]
[Ideal hours: 8]

**Comment by samgo1** [comment]
@lkadian @laurawheatley I created a branch named `feat/CaptureTimeDelay_20` off that we can use to collaborate on this task

**Comment by samgo1** [comment]
@aa-software2112 @anthonyle17 @KrishnaPatel1 @laurawheatley @lkadian @Lussier115 I started writing functions for backend in the above branch, you can start looking at the code and let me know if you feel that we should implement it in a different way

**Comment by lkadian** [comment]
@samgo1 @laurawheatley 

I completed most of the feature; there might be some stuff I am missing. It would be a good idea to run this branch and let me know if it runs like we want it to.

The UI isn't implemented exactly like the mockup (mainly I just have one countdown on the UI, while on the mockup we have a different countdown before starting and after starting the countdown), it's a minor thing, but we can change that if we want it exactly like the mockup. I also left a few //TODO comments at places where improvements could be made.

@aa-software2112 @KrishnaPatel1 @anthonyle17 @Lussier115 feel free to run it on phone/emulator also and let me know if it works as we wanted.

**Comment by Lussier115** [comment]
You did not use the front end branch? It should be exactly the same as the mockup if you used it.

**Comment by Lussier115** [comment]
You did not use the front end branch? It should be exactly the same as the mockup. Otherwise good work, I'll be testing it probably tonight.

**Comment by lkadian** [comment]
@Lussier115 I did merge your front end branch, but ended up switching how the countdown timer looks slightly, you will see. But this can be changed

**Comment by Lussier115** [comment]
From what I can see the countdown timer is at the top? Any reason for the change? 
There is also another element with the id countdown that is not being used.

Personally, I would have kept the countdown at the bottom and also the circle I had created to go with it like the mock up.

**Comment by lkadian** [comment]
The circle countdown element was displaying weirdly (as an oval not circle) on my phone. Also the countdown above the shutter button was overlapping it on my phone and was looking weird. Of course this is an easy fix but I was working on the backend so I decided to not bother fixing that and just get the backend to work. Now that it's done I can go back to switch it how it looks in the mockup. So yeah it's not a final design, I'll change that tonight and pull request.

**Comment by anthonyle17** [comment]
Tested the branch and the countdown functionality works well. Since you @lkadian were working on the backend only, you can leave the frontend fix to us.

@Lussier115 worked on the frontend, but do you mind if I do it since I only have test writings for this sprint? I'd like to work on the frontend a bit, this would be a good opportunity. Let me know! Thanks

**Comment by Lussier115** [comment]
I do not have much either than the frontend. I would have lowered the countdown to make it more similar to the mockup and at the same time work on Mockup for UI Redesign #49

**Comment by samgo1** [comment]
@laurawheatley @lkadian anything else needs to be done here? I think @aa-software2112 mentioned that we need an acceptance test, correct?

**Comment by anthonyle17** [comment]
@samgo1 That is correct, either @laurawheatley or @lkadian needs to fill in the acceptance test [doc](https://docs.google.com/document/d/1HGzpjKrG4jJgbl7bbsN1vCuTvf9UJ68ynRmPkmYnWYw/edit) entitled "Acceptance Tests" in the Google Drive in order for me and @aa-software2112 to write unit tests.

**Comment by KrishnaPatel1** [comment]
@lkadian already filled out the acceptance test doc. I've written part of the acceptance test on my branch.
