### ISSUE TITLE
Starting and cancelling a countdown immediately starts burst mode and won't leave

### ISSUE THREAD

**Issue by lkadian** [aa-software2112/SOEN390_SimpleCamera#76]
1. Select a countdown (e.g. 10 sec) and press shutter to start it.
   2. Stop the countdown right away (before 2 seconds elapse).
   3. The camera starts entering burst mode and never leaves. Shouldn't happen

**Comment by Lussier115** [comment]
Checking this ASAP, shouldn't take too long

**Comment by lkadian** [comment]
Bug was that upon releasing the shutter button, it was only removing mBurstRunnable from the queue, it should also remove mBurstSetup
